name: Python CI
on: [push, pull_request]  

jobs:
  verify:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          
      - name: Verify Python
        run: |
          python --version
          pip install -r requirements.txt